# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title count loss function 
#' @description count loss function
#' @param x Independent variable (dataframe)
#' @param y Dependent variable (dataframe)
#' @param beta coefficent
#' @param i ith unit
#' @return The loss function for the i-th unit
#' @examples
#' \dontrun{
#' x <- matrix(1:9, nrow = 3, ncol = 3)
#' y <- matrix(10:18, nrow = 3, ncol = 3)
#' count(x, y, 1, 1)
#' }
#' @export
count <- function(x, y, beta, i) {
    .Call('_SA24204168_count', PACKAGE = 'SA24204168', x, y, beta, i)
}

